// Desafios prontos
export const desafiosProntos = [
    {
      id: 'd11',
      title: 'Calculadora Web',
      description: 'Crie uma calculadora simples usando HTML, CSS e JavaScript.',
      level: 'iniciante',
      xp: 70,
      link: '/challenges/d11',
    },
    {
      id: 'd12',
      title: 'To-Do List com React',
      description: 'Implemente uma lista de tarefas com React, incluindo edição e remoção.',
      level: 'iniciante',
      xp: 90,
      link: '/challenges/d12',
    },
    {
      id: 'd13',
      title: 'API de Clima',
      description: 'Consuma uma API de clima e exiba a previsão para sua cidade.',
      level: 'intermediário',
      xp: 120,
      link: '/challenges/d13',
    },
    {
      id: 'd14',
      title: 'Jogo da Memória',
      description: 'Crie um jogo da memória com cartas e pontuação.',
      level: 'intermediário',
      xp: 150,
      link: '/challenges/d14',
    },
    {
      id: 'd15',
      title: 'Chat em Tempo Real',
      description: 'Implemente um chat usando WebSocket ou Firebase.',
      level: 'avançado',
      xp: 250,
      link: '/challenges/d15',
    },
    {
      id: 'd16',
      title: 'Sistema de Notas',
      description: 'Crie um sistema CRUD para notas pessoais com autenticação.',
      level: 'intermediário',
      xp: 130,
      link: '/challenges/d16',
    },
    {
      id: 'd17',
      title: 'Blog Markdown',
      description: 'Desenvolva um blog onde os posts são escritos em Markdown.',
      level: 'avançado',
      xp: 200,
      link: '/challenges/d17',
    },
    {
      id: 'd18',
      title: 'Sistema de Votação',
      description: 'Implemente um sistema de votação online com resultados em tempo real.',
      level: 'intermediário',
      xp: 160,
      link: '/challenges/d18',
    },
  {
    id: 'd1',
    title: 'Landing Page Responsiva',
    description: 'Crie uma landing page moderna usando React e Tailwind.',
    level: 'intermediário',
    xp: 150,
    link: '/challenges/d1',
  },
  {
    id: 'd2',
    title: 'API REST com Node',
    description: 'Implemente uma API RESTful com autenticação JWT.',
    level: 'avançado',
    xp: 200,
    link: '/challenges/d2',
  },
  {
    id: 'd3',
    title: 'CRUD Fullstack',
    description: 'Integre frontend e backend com autenticação e CRUD.',
    level: 'iniciante',
    xp: 100,
    link: '/challenges/d3',
  },
  {
    id: 'd4',
    title: 'Portfólio Pessoal',
    description: 'Desenvolva um portfólio com animações e projetos destacados.',
    level: 'iniciante',
    xp: 80,
    link: '/challenges/d4',
  },
  {
    id: 'd5',
    title: 'Dashboard com Gráficos',
    description: 'Crie um dashboard interativo usando Chart.js ou Recharts.',
    level: 'intermediário',
    xp: 160,
    link: '/challenges/d5',
  },
  {
    id: 'd6',
    title: 'Bot Telegram',
    description: 'Implemente um bot para Telegram que responde comandos.',
    level: 'avançado',
    xp: 220,
    link: '/challenges/d6',
  },
  {
    id: 'd7',
    title: 'Clone do Instagram',
    description: 'Faça um clone simples do Instagram com upload de imagens.',
    level: 'intermediário',
    xp: 180,
    link: '/challenges/d7',
  },
  {
    id: 'd8',
    title: 'API GraphQL',
    description: 'Crie uma API GraphQL para consultas e mutações.',
    level: 'avançado',
    xp: 210,
    link: '/challenges/d8',
  },
  {
    id: 'd9',
    title: 'Sistema de Login com OAuth',
    description: 'Implemente login social com Google ou GitHub.',
    level: 'intermediário',
    xp: 140,
    link: '/challenges/d9',
  },
  {
    id: 'd10',
    title: 'Landing Page Animada',
    description: 'Use GSAP ou Framer Motion para criar animações.',
    level: 'iniciante',
    xp: 90,
    link: '/challenges/d10',
  },
];

// Projetos prontos
export const projetosProntos = [
  {
    id: 'p1',
    name: 'Social Network',
    description: 'Rede social para devs com feed, perfil e chat.',
    status: 'pronto',
    link: '/projects/p1',
  },
  {
    id: 'p2',
    name: 'E-commerce Completo',
    description: 'Loja virtual com carrinho, pagamentos e painel admin.',
    status: 'pronto',
    link: '/projects/p2',
  },
  {
    id: 'p3',
    name: 'Blog Tech',
    description: 'Blog de tecnologia com comentários e ranking de posts.',
    status: 'pronto',
    link: '/projects/p3',
  },
];
